Vagrant.configure("2") do |config|
  config.vm.define "vzurera-S" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.box_version = "12.20250126.1"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.hostname = "vzurera-S"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 8080, host: 8888
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "vzurera-S"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    end
    server.vm.provision "shell", inline: "mkdir -p /tmp/k3s_config && chown vagrant:vagrant /tmp/k3s_config"
    server.vm.provision "file", source: "./config/application.yaml", destination: "/tmp/k3s_config/application.yaml"
    server.vm.provision "shell", path: "scripts/server.sh", env: { "K3S_IP" => "192.168.56.110" }
  end
end
