installCertmanager: false

global:
    edition: ce
    hosts:
        domain: local
        gitlab:
            name: gitlab.local
        https: false
        ssh: false
    ingress:
        configureCertmanager: false
        enabled: true
        class: traefik
        annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
        tls:
            enabled: false
    kas:
        enabled: false
    application:
        allowClusterRoles: false
    initialRootPassword:
        secret: gitlab-root-password
        key: initial_root_password

certmanager-issuer:
    email: admin@gitlab.local

nginx-ingress:
    enabled: false

prometheus:
    install: false

gitlab-runner:
    install: false

registry:
    enabled: false

gitlab:
    gitaly:
        resources:
            requests:
                memory: 256Mi
                cpu: 50m
            limits:
                memory: 512Mi
    gitlab-shell:
        enabled: false
    webservice:
        replicaCount: 1
        workerProcesses: 1
        minReplicas: 1
        maxReplicas: 1
        resources:
            requests:
                memory: 900Mi
                cpu: 100m
            limits:
                memory: 1.5Gi
    sidekiq:
        concurrency: 5
        replicas: 1
        resources:
            requests:
                memory: 256Mi
                cpu: 100m
    toolbox:
        resources:
            requests:
                memory: 256Mi
                cpu: 50m

postgresql:
    metrics:
        enabled: false
    primary:
        resources:
            requests:
                memory: 256Mi

redis:
    metrics:
        enabled: false
    master:
        resources:
            requests:
                memory: 64Mi

