Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  SCRIPT = <<-SHELL
    if [ ! -f /swapfile ]; then
      fallocate -l 1G /swapfile
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi
    if ! command -v k3s &> /dev/null; then
      wget -qO- https://get.k3s.io | K3S_TOKEN=super_secret_token bash
    fi
  SHELL

  config.vm.define "vzurera-S" do |server|
    server.vm.hostname = "vzurera-S"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "vzurera-S"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    end
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: SCRIPT, env: {
      "INSTALL_K3S_EXEC" => "server --node-ip=192.168.56.110 --disable=traefik --disable=servicelb --disable=metrics-server --disable=local-storage",
      "K3S_KUBECONFIG_MODE" => "644"
    }
  end

  config.vm.define "vzurera-SW" do |worker|
    worker.vm.hostname = "vzurera-SW"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "vzurera-SW"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    end
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", inline: SCRIPT, env: {
      "INSTALL_K3S_EXEC" => "agent --node-ip=192.168.56.111",
      "K3S_URL" => "https://192.168.56.110:6443"
    }
  end

end
