Vagrant.configure("2") do |config|
  config.vm.define "vzurera-S" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.box_version = "12.20250126.1"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.hostname = "vzurera-S"
    server.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    server.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "vzurera-S"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    end
    server.vm.provision "shell", inline: "mkdir -p /tmp/k3s_config && chown vagrant:vagrant /tmp/k3s_config"
    server.vm.provision "file", source: "./config/application.yaml", destination: "/tmp/k3s_config/application.yaml"
    server.vm.provision "file", source: "./config/argocd-ingress.yaml", destination: "/tmp/k3s_config/argocd-ingress.yaml"
    server.vm.provision "file", source: "./config/gitlab-values.yaml", destination: "/tmp/k3s_config/gitlab-values.yaml"
    server.vm.provision "shell", path: "scripts/install.sh"
    server.vm.provision "shell", path: "scripts/start.sh", run: "always"
  end
end
