Vagrant.configure("2") do |config|
  provision_env = {
    "GITLAB_USER" => ENV.fetch("GITLAB_USER", "vzurera"),
    "GITLAB_PASS" => ENV.fetch("GITLAB_PASS", "aA123456789*"),
    "GITLAB_USERPASS" => ENV.fetch("GITLAB_USERPASS", "aA123456789*"),
    "GITLAB_REPO" => ENV.fetch("GITLAB_REPO", "inception-of-things"),
    "ARGOCD_PASS" => ENV.fetch("ARGOCD_PASS", "aA123456789*")
  }

  config.vm.define "vzurera-S" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.box_version = "12.20250126.1"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.hostname = "vzurera-S"
    server.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "vzurera-S"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
    end
    server.vm.provision "file", source: "config", destination: "/tmp/config"
    server.vm.provision "shell", inline: "chown -R vagrant:vagrant /tmp/config"
    server.vm.provision "shell", path: "scripts/install.sh", env: provision_env
    server.vm.provision "shell", path: "scripts/start.sh", run: "always", env: provision_env
  end
end
